### ISSUE TITLE
error while running the codes given in this repository

### ISSUE THREAD

**Issue by ashish210111** [jcarcamo/sar-deep-rl#1]
dear sir I am using UE 4.24, AirSim with anaconda/spyder. I am able to run sample codes for drones given in PythonCLient folder. But when i am trying to run  the code given in this repository then i am having some error

![Untitled](https://user-images.githubusercontent.com/64783760/81483115-52602a00-9259-11ea-94ba-321c762024d4.png)

**Comment by jcarcamo** [comment]
It looks like you're  trying to give a path with single \\
In programming languages typically \ is an escape character (one that is used to print special characters line newline \n)

Either use forward slash / or \\\\ to separate your path
